name: Wake Streamlit App

on:
  schedule:
    - cron: "0 */4 * * *" # run every 4 hours
  workflow_dispatch: # allows manual trigger

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium script
        env:
          STREAMLIT_APP_URL: "https://your-app-name.streamlit.app/"
        run: python main.py
